version: '3.8'

services:
  
  sanity:
    build:
      context: ./app/sanity
      dockerfile: ${NODE_ENV:-development}.Dockerfile
    ports:
      - "${PORT:-3333}:3333"
    volumes:
      - ./app/sanity:/app/sanity
      - /app/sanity/node_modules
      - /app/sanity/.sanity
    environment:
      - SANITY_STUDIO_PUBLIC_SANITY_PROJECT_ID=${SANITY_STUDIO_PUBLIC_SANITY_PROJECT_ID:-r9iqr1x2}
      - SANITY_STUDIO_PUBLIC_SANITY_DATASET=${SANITY_STUDIO_PUBLIC_SANITY_DATASET:-production}
      - SANITY_STUDIO_PUBLIC_SANITY_DATASET_DEV=${SANITY_STUDIO_PUBLIC_SANITY_DATASET_DEV:-testing}
      - SANITY_API_VERSION=${SANITY_API_VERSION:-2024-03-21}
    restart: unless-stopped

  web:
      build:
        context: ./app
        dockerfile: ${NODE_ENV:-development}.Dockerfile
      ports:
        - "${PORT:-8080}:3000"
      volumes:
        - ./app:/app
        - /app/node_modules
        - /app/.next
      environment:
        - NODE_ENV=${NODE_ENV:-development}
        - NEXT_PUBLIC_SANITY_PROJECT_ID=${NEXT_PUBLIC_SANITY_PROJECT_ID:-r9iqr1x2}
        - NEXT_PUBLIC_SANITY_DATASET=${NEXT_PUBLIC_SANITY_DATASET:-production}
        - NEXT_PUBLIC_SANITY_DATASET_DEV=${NEXT_PUBLIC_SANITY_DATASET_DEV:-testing}
        - SANITY_API_VERSION=${SANITY_API_VERSION:-2024-03-21}
        # - NEXT_PUBLIC_GA_ID=${NEXT_PUBLIC_GA_ID:-G-V538SKHV3E}
        # - WATCHPACK_POLLING=true
      restart: unless-stopped
      
